In [142]:
# TODO: Import the required libaries
import pandas as pd

In [143]:
# TODO: Read the required dataset
sephora_data = pd.read_csv("sephora_website_dataset.csv")

In [144]:
# TODO: Preview the data
sephora_data.head()

,id,brand,category,name,size,rating,number_of_reviews,love,price,value_price,...,MarketingFlags,MarketingFlags_content,options,details,how_to_use,ingredients,online_only,exclusive,limited_edition,limited_time_offer
0,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,5 x 0.16oz/5mL,4.0,4,3002,66.0,75.0,...,True,online only,no options,This enchanting set comes in a specially handc...,Suggested Usage:-Fragrance is intensified by t...,Arancia di Capri Eau de Toilette: Alcohol Dena...,1,0,0,0
1,2044816,Acqua Di Parma,Cologne,Colonia,0.7 oz/ 20 mL,4.5,76,2700,66.0,66.0,...,True,online only,- 0.7 oz/ 20 mL Spray - 1.7 oz/ 50 mL Eau d...,An elegant timeless scent filled with a fresh-...,no instructions,unknown,1,0,0,0
2,1417567,Acqua Di Parma,Perfume,Arancia di Capri,5 oz/ 148 mL,4.5,26,2600,180.0,180.0,...,True,online only,- 1oz/30mL Eau de Toilette - 2.5 oz/ 74 mL E...,Fragrance Family: Fresh Scent Type: Fresh Citr...,no instructions,Alcohol Denat.- Water- Fragrance- Limonene- Li...,1,0,0,0
3,1417617,Acqua Di Parma,Perfume,Mirto di Panarea,2.5 oz/ 74 mL,4.5,23,2900,120.0,120.0,...,True,online only,- 1 oz/ 30 mL Eau de Toilette Spray - 2.5 oz/...,Panarea near Sicily is an an island suspended ...,no instructions,unknown,1,0,0,0
4,2218766,Acqua Di Parma,Fragrance,Colonia Miniature Set,5 x 0.16oz/5mL,3.5,2,943,72.0,80.0,...,True,online only,no options,The Colonia Miniature Set comes in an iconic A...,Suggested Usage:-Fragrance is intensified by t...,Colonia: Alcohol Denat.- Water- Fragrance- Lim...,1,0,0,0

# REMOVE/DROP UNNCESSARY COLUMNS

In [145]:
#Remove Unnecessary Columns PT 1
sephora_data = sephora_data.drop(columns=['size','MarketingFlags','MarketingFlags_content','options','details','online_only','exclusive'])

In [146]:
#Remove Unnecessary Columns PT 2
sephora_data = sephora_data.drop(columns=['URL','value_price','limited_edition','limited_time_offer'])

In [147]:
sephora_data.head()

,id,brand,category,name,rating,number_of_reviews,love,price,how_to_use,ingredients
0,2218774,Acqua Di Parma,Fragrance,Blu Mediterraneo MINIATURE Set,4.0,4,3002,66.0,Suggested Usage:-Fragrance is intensified by t...,Arancia di Capri Eau de Toilette: Alcohol Dena...
1,2044816,Acqua Di Parma,Cologne,Colonia,4.5,76,2700,66.0,no instructions,unknown
2,1417567,Acqua Di Parma,Perfume,Arancia di Capri,4.5,26,2600,180.0,no instructions,Alcohol Denat.- Water- Fragrance- Limonene- Li...
3,1417617,Acqua Di Parma,Perfume,Mirto di Panarea,4.5,23,2900,120.0,no instructions,unknown
4,2218766,Acqua Di Parma,Fragrance,Colonia Miniature Set,3.5,2,943,72.0,Suggested Usage:-Fragrance is intensified by t...,Colonia: Alcohol Denat.- Water- Fragrance- Lim...

# SPLIT INGREDIENTS

## It's only running the "-" split, how do we capture : and - maybe explore regex

In [148]:
ingredient_split = sephora_data['ingredients'].str.split(':', expand=True)

In [149]:
ingredient_split.head()

,0,1,2,3,4,5,6,7,8,9,...,33,34,35,36,37,38,39,40,41,42
0,Arancia di Capri Eau de Toilette,Alcohol Denat.- Water- Fragrance- Limonene- L...,Alcohol Denat.- Fragrance- Water- Limonene- Et...,Alcohol Denat.- Fragrance- Water- Limonene- E...,Alcohol Denat.- Fragrance- Water- Limonene- Li...,Alcohol Denat.- Water- Fragrance- Limonene- L...,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
1,unknown,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,Alcohol Denat.- Water- Fragrance- Limonene- Li...,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,unknown,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,Colonia,Alcohol Denat.- Water- Fragrance- Limonene- H...,Alcohol Denat.- Fragrance- Water- Limonene- E...,alcohol denat.- Water- Fragrance- Limonene- H...,Alcohol Denat.- Water- Fragrance- Limonene- He...,Alcohol Denat.- Water- Fragrance- Limonene- L...,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None

In [157]:
ingredient_split_2 = ingredient_split[1].str.split('-', expand=True)

In [158]:
ingredient_split_2.head()

,0,1,2,3,4,5,6,7,8,9,...,89,90,91,92,93,94,95,96,97,98
0,Alcohol Denat.,Water,Fragrance,Limonene,Linalool,Ethylhexyl Methoxycinnamate,Citral,Butyl Methoxydibenzoylmethane,Ethylhexyl Salicylate,BHT,...,None,None,None,None,None,None,None,None,None,None
1,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,None,None,None,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,Alcohol Denat.,Water,Fragrance,Limonene,Hydroxycitronellal,Linalool,Citral,Benzyl Salicylate,Coumarin,Eugenol,...,None,None,None,None,None,None,None,None,None,None

# CLEAN UP INGREDIENT LIST DF

In [106]:
#Instead of dropping >500 columns, reselect columns to be kept for ingredient DF
ingredient_list = ingredient_split[[1,2,3,4,5,6,7]]

In [107]:
ingredient_list.head()

,1,2,3,4,5,6,7
0,Water,Fragrance,Limonene,Linalool,Ethylhexyl Methoxycinnamate,Citral,Butyl Methoxydibenzoylmethane
1,None,None,None,None,None,None,None
2,Water,Fragrance,Limonene,Linalool,Ethylhexylmethoxycinnamate,Citral,Butylmethoxydibenzoylmethane
3,None,None,None,None,None,None,None
4,Water,Fragrance,Limonene,Hydroxycitronellal,Linalool,Citral,Benzyl Salicylate

In [108]:
#Rename Ingredient List
ingredient_list.rename(columns={1: "Ingredient 1", 2: "Ingredient 2",3: "Ingredient 3", 4: "Ingredient 4",5: "Ingredient 5", 6: "Ingredient 6",7: "Ingredient 7"})

,Ingredient 1,Ingredient 2,Ingredient 3,Ingredient 4,Ingredient 5,Ingredient 6,Ingredient 7
0,Water,Fragrance,Limonene,Linalool,Ethylhexyl Methoxycinnamate,Citral,Butyl Methoxydibenzoylmethane
1,None,None,None,None,None,None,None
2,Water,Fragrance,Limonene,Linalool,Ethylhexylmethoxycinnamate,Citral,Butylmethoxydibenzoylmethane
3,None,None,None,None,None,None,None
4,Water,Fragrance,Limonene,Hydroxycitronellal,Linalool,Citral,Benzyl Salicylate
...,...,...,...,...,...,...,...
9163,Rose Quartz Extract: Hydrates dry skin. Aqua ...,Butylene Glycol,Lecithin,Glycerin,1,2,Hexanediol
9164,Pentaerythrityl Tetraethylhexanoate,Triisostearyl Citrate,Ethylene/Propylene/Styrene Copolymer,Ricinus Communis (Castor) Seed Oil,Aroma,CI 77891 (Titanium Dioxide),Calcium Aluminum Borosilicate
9165,Dimethicone,Isohexadecane,Polymethylsilsesquioxane,Butylene Glycol,Polysilicone,11,Cetyl Peg/Ppg
9166,None,None,None,None,None,None,None
9167,None,None,None,None,None,None,None